// Maps icon name strings (stored in workspace config JSON) to lucide-react components

import {
  Package, Wrench, Calendar, FileText, Users, ShoppingCart,
  Receipt, Truck, Warehouse, AlertTriangle, Clock, Car,
  Settings, Settings2, Building2, ArrowRightLeft, FolderTree, Star,
  LayoutDashboard, ChevronRight, Home, Monitor, Bell, Activity,
  DollarSign, TrendingUp, CreditCard, ClipboardList, Shield,
  History, FileInput, Loader2, RefreshCw, Plus, Minus, Edit,
  Trash2, GripVertical, ChevronUp, ChevronDown, X, Check,
  BarChart3, UtensilsCrossed, LayoutGrid, ChefHat, Sparkles,
  ShieldCheck,
  // Sidebar icons
  Hash, ClipboardCheck, PackageCheck, Thermometer, CalendarCheck,
  Ship, ArrowLeftRight, Wallet, Banknote, UserCheck, SlidersHorizontal,
  Map, BookOpen, Target, CheckSquare, Mail, List, Landmark,
  Scale, PieChart, ArrowDownRight, ArrowUpRight, CalendarDays,
  Boxes, Bookmark, Lock, PlayCircle, AlertCircle, Calculator,
  Layers, Play, Printer, User, Search, Barcode, Tag,
  type LucideIcon,
} from 'lucide-react'

export const ICON_MAP: Record<string, LucideIcon> = {
  Package,
  Wrench,
  Calendar,
  FileText,
  Users,
  ShoppingCart,
  Receipt,
  Truck,
  Warehouse,
  AlertTriangle,
  Clock,
  Car,
  Settings,
  Settings2,
  Building2,
  ArrowRightLeft,
  FolderTree,
  Star,
  LayoutDashboard,
  ChevronRight,
  Home,
  Monitor,
  Bell,
  Activity,
  DollarSign,
  TrendingUp,
  CreditCard,
  ClipboardList,
  Shield,
  History,
  FileInput,
  Loader2,
  RefreshCw,
  Plus,
  Minus,
  Edit,
  Trash2,
  GripVertical,
  ChevronUp,
  ChevronDown,
  X,
  Check,
  BarChart3,
  UtensilsCrossed,
  LayoutGrid,
  ChefHat,
  Sparkles,
  ShieldCheck,
  // Sidebar icons
  Hash,
  ClipboardCheck,
  PackageCheck,
  Thermometer,
  CalendarCheck,
  Ship,
  ArrowLeftRight,
  Wallet,
  Banknote,
  UserCheck,
  SlidersHorizontal,
  Map,
  BookOpen,
  Target,
  CheckSquare,
  Mail,
  List,
  Landmark,
  Scale,
  PieChart,
  ArrowDownRight,
  ArrowUpRight,
  CalendarDays,
  Boxes,
  Bookmark,
  Lock,
  PlayCircle,
  AlertCircle,
  Calculator,
  Layers,
  Play,
  Printer,
  User,
  Search,
  Barcode,
  Tag,
}

export function getIcon(name: string): LucideIcon {
  return ICON_MAP[name] || Package
}
