'use client'

import { useState } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Warehouse, Plus, Trash2, ChevronDown, ChevronUp, MapPin, Star } from 'lucide-react'
import type { SetupWizardData, WarehouseInput } from '@/lib/setup/create-seed-data'
import { useStepSuggestions } from './useStepSuggestions'
import { AISuggestionBanner } from './AISuggestionChip'
import { FormInput, FormField, FormTextarea } from '@/components/ui/form-elements'

interface StepWarehousesProps {
  data: SetupWizardData
  companySlug: string
  businessType: string
  country: string
  countryName: string
  currency: string
  companyName: string
  aiEnabled?: boolean
  onChange: (updates: Partial<SetupWizardData>) => void
}

function generateCode(name: string): string {
  return name.toUpperCase().replace(/\s+/g, '_').slice(0, 10)
}

export function StepWarehouses({ data, companySlug, businessType, country, countryName, currency, companyName, aiEnabled, onChange }: StepWarehousesProps) {
  const [expandedIdx, setExpandedIdx] = useState<number | null>(null)

  const { suggestions, loading, dismissed, dismiss } = useStepSuggestions<{ suggestedNames: string[] }>({
    step: 'warehouses',
    context: { businessType, country, countryName, currency, companyName },
    companySlug,
    enabled: aiEnabled,
  })

  const warehouses: WarehouseInput[] = data.warehouses || [
    { name: 'Main Warehouse', code: 'MAIN_WAREH', isDefault: true },
  ]

  const updateWarehouse = (index: number, updates: Partial<WarehouseInput>) => {
    const updated = [...warehouses]
    updated[index] = { ...updated[index], ...updates }
    onChange({ warehouses: updated })
  }

  const updateName = (index: number, name: string) => {
    const updated = [...warehouses]
    const currentCode = updated[index].code
    const wasAutoGenerated = currentCode === generateCode(updated[index].name)
    updated[index] = {
      ...updated[index],
      name,
      ...(wasAutoGenerated ? { code: generateCode(name) } : {}),
    }
    onChange({ warehouses: updated })
  }

  const setDefault = (index: number) => {
    const updated = warehouses.map((w, i) => ({
      ...w,
      isDefault: i === index,
    }))
    onChange({ warehouses: updated })
  }

  const addWarehouse = () => {
    if (warehouses.length >= 5) return
    const newWarehouse: WarehouseInput = {
      name: '',
      code: '',
      isDefault: false,
    }
    onChange({ warehouses: [...warehouses, newWarehouse] })
  }

  const removeWarehouse = (index: number) => {
    if (warehouses.length <= 1) return
    const updated = warehouses.filter((_, i) => i !== index)
    // If the removed warehouse was the default, make the first one default
    if (!updated.some(w => w.isDefault) && updated.length > 0) {
      updated[0].isDefault = true
    }
    // Adjust expanded index
    if (expandedIdx === index) {
      setExpandedIdx(null)
    } else if (expandedIdx !== null && expandedIdx > index) {
      setExpandedIdx(expandedIdx - 1)
    }
    onChange({ warehouses: updated })
  }

  const toggleExpanded = (index: number) => {
    setExpandedIdx(expandedIdx === index ? null : index)
  }

  const applyWarehouseSuggestions = () => {
    if (!suggestions?.suggestedNames?.length) return
    const newWarehouses: WarehouseInput[] = suggestions.suggestedNames.map((name, i) => ({
      name,
      code: generateCode(name),
      isDefault: i === 0,
    }))
    onChange({ warehouses: newWarehouses })
  }

  return (
    <div className="space-y-5">
      {/* Step Header */}
      <div>
        <h2 className="text-lg font-bold text-gray-900 dark:text-white tracking-tight">
          Warehouses
        </h2>
        <p className="text-sm text-gray-400 dark:text-gray-500 mt-0.5">
          Set up your storage locations. You can add up to 5 warehouses.
        </p>
      </div>

      {/* AI suggestion banner */}
      {!dismissed.has('warehouses') && (
        <AISuggestionBanner
          items={suggestions?.suggestedNames || []}
          loading={loading}
          itemLabel="warehouse names"
          onApplyAll={applyWarehouseSuggestions}
          onDismiss={() => dismiss('warehouses')}
        />
      )}

      {/* Warehouse Cards */}
      <div className="space-y-3">
        <AnimatePresence>
        {warehouses.map((warehouse, index) => (
          <motion.div
            key={index}
            layout
            initial={{ opacity: 0, scale: 0.97 }}
            animate={{ opacity: 1, scale: 1 }}
            exit={{ opacity: 0, scale: 0.97 }}
            transition={{ duration: 0.2 }}
            className={`rounded-xl border p-4 transition-all duration-200 ${
              warehouse.isDefault
                ? 'border-blue-200 dark:border-blue-800/60 bg-gradient-to-r from-blue-50/80 to-white dark:from-blue-950/20 dark:to-slate-800/40 shadow-sm shadow-blue-500/5'
                : 'border-gray-200/60 dark:border-gray-700/50 bg-white dark:bg-slate-800/40'
            }`}
          >
            {/* Header row */}
            <div className="flex items-start gap-3">
              <div className="flex items-center justify-center w-9 h-9 rounded-lg bg-orange-50 dark:bg-orange-900/30 flex-shrink-0 mt-0.5">
                <Warehouse size={16} className="text-orange-600 dark:text-orange-400" />
              </div>
              <div className="flex-1 grid grid-cols-2 gap-3">
                <FormField label="Name" required>
                  <FormInput
                    value={warehouse.name}
                    onChange={(e) => updateName(index, e.target.value)}
                    placeholder="e.g. Main Warehouse"
                  />
                </FormField>
                <FormField label="Code">
                  <FormInput
                    value={warehouse.code}
                    onChange={(e) => updateWarehouse(index, { code: e.target.value.toUpperCase().slice(0, 10) })}
                    className="font-mono"
                    placeholder="AUTO"
                    maxLength={10}
                  />
                </FormField>
              </div>

              <div className="flex items-center gap-1 pt-1">
                {warehouse.isDefault ? (
                  <span className="inline-flex items-center gap-1 px-2.5 py-1 rounded-lg text-[11px] font-semibold bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-300">
                    <Star size={10} fill="currentColor" />
                    Default
                  </span>
                ) : (
                  <button
                    onClick={() => setDefault(index)}
                    className="inline-flex items-center gap-1 px-2 py-1 rounded-lg text-[11px] font-medium text-gray-400 dark:text-gray-500 hover:text-blue-600 dark:hover:text-blue-400 hover:bg-blue-50 dark:hover:bg-blue-950/30 transition-all"
                    title="Set as default"
                  >
                    <Star size={10} />
                  </button>
                )}
                <button
                  onClick={() => toggleExpanded(index)}
                  className="p-1.5 rounded-lg text-gray-400 hover:text-gray-600 dark:hover:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700 transition-all"
                  title={expandedIdx === index ? 'Hide details' : 'Show details'}
                >
                  {expandedIdx === index ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
                </button>
                <button
                  onClick={() => removeWarehouse(index)}
                  disabled={warehouses.length <= 1}
                  className="p-1.5 rounded-lg text-gray-400 hover:text-red-500 hover:bg-red-50 dark:hover:bg-red-950/30 transition-all disabled:opacity-20 disabled:cursor-not-allowed disabled:hover:bg-transparent disabled:hover:text-gray-400"
                  title="Remove warehouse"
                >
                  <Trash2 size={16} />
                </button>
              </div>
            </div>

            {/* Collapsible details */}
            {expandedIdx === index && (
              <div className="mt-4 pt-4 border-t border-gray-100 dark:border-gray-700/40 space-y-3 ml-12">
                <FormField label="Address">
                  <FormTextarea
                    value={warehouse.address || ''}
                    onChange={(e) => updateWarehouse(index, { address: e.target.value })}
                    rows={2}
                    className="resize-none min-h-0"
                    placeholder="Street address, city, etc."
                  />
                </FormField>
                <div className="grid grid-cols-2 gap-3">
                  <FormField label="Phone">
                    <FormInput
                      type="tel"
                      value={warehouse.phone || ''}
                      onChange={(e) => updateWarehouse(index, { phone: e.target.value })}
                      placeholder="+94 xx xxx xxxx"
                    />
                  </FormField>
                  <FormField label="Email">
                    <FormInput
                      type="email"
                      value={warehouse.email || ''}
                      onChange={(e) => updateWarehouse(index, { email: e.target.value })}
                      placeholder="warehouse@company.com"
                    />
                  </FormField>
                </div>
              </div>
            )}
          </motion.div>
        ))}
        </AnimatePresence>

        {/* Add warehouse button */}
        <button
          onClick={addWarehouse}
          disabled={warehouses.length >= 5}
          className="flex items-center gap-2 py-3 border-2 border-dashed border-gray-200 dark:border-gray-700/50 rounded-xl text-sm text-gray-400 dark:text-gray-500 hover:border-blue-300 hover:text-blue-600 dark:hover:border-blue-700 dark:hover:text-blue-400 transition-all w-full justify-center disabled:opacity-30 disabled:cursor-not-allowed disabled:hover:border-gray-200 disabled:hover:text-gray-400"
        >
          <Plus size={16} />
          Add Warehouse
        </button>
      </div>

      {/* Tip */}
      <div className="flex items-start gap-2.5 px-4 py-3 bg-gray-50/80 dark:bg-slate-800/30 rounded-lg border border-gray-100 dark:border-gray-700/30">
        <MapPin size={14} className="text-gray-400 dark:text-gray-500 flex-shrink-0 mt-0.5" />
        <p className="text-xs text-gray-500 dark:text-gray-400">
          Warehouse address and contact details will appear on letterheads and printed documents.
        </p>
      </div>
    </div>
  )
}
